default: &default
  required_authentination: false
  database: "gono-<%= Rails.env %>"
  server: 127.0.0.1:5984

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  required_authentination: true
  username: admin
  password: adminsecrets
